find_package(Git QUIET)

set(MINITUN_GIT_COMMIT "unknown")
set(MINITUN_GIT_TAG "")
if(Git_FOUND AND EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/.git")
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --short=12 HEAD
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        RESULT_VARIABLE MINITUN_GIT_RESULT
        OUTPUT_VARIABLE MINITUN_GIT_OUTPUT
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(MINITUN_GIT_RESULT EQUAL 0 AND NOT MINITUN_GIT_OUTPUT STREQUAL "")
        set(MINITUN_GIT_COMMIT "${MINITUN_GIT_OUTPUT}")
    endif()

    execute_process(
        COMMAND "${GIT_EXECUTABLE}" describe --tags --exact-match --match "v[0-9]*" HEAD
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        RESULT_VARIABLE MINITUN_TAG_RESULT
        OUTPUT_VARIABLE MINITUN_TAG_OUTPUT
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    if(MINITUN_TAG_RESULT EQUAL 0 AND MINITUN_TAG_OUTPUT MATCHES "^v.+")
        string(SUBSTRING "${MINITUN_TAG_OUTPUT}" 1 -1 MINITUN_GIT_TAG)
    endif()
endif()

if(NOT MINITUN_GIT_TAG STREQUAL "")
    set(MINITUN_VERSION_STRING "${MINITUN_GIT_TAG}")
elseif(NOT MINITUN_GIT_COMMIT STREQUAL "unknown")
    set(MINITUN_VERSION_STRING "${PROJECT_VERSION}-dev+g${MINITUN_GIT_COMMIT}")
else()
    set(MINITUN_VERSION_STRING "${PROJECT_VERSION}")
endif()

function(minitun_apply_version_definitions target)
    target_compile_definitions("${target}"
        PRIVATE
            MINITUN_VERSION="${MINITUN_VERSION_STRING}"
            MINITUN_GIT_COMMIT="${MINITUN_GIT_COMMIT}"
            MINITUN_BUILD_TYPE="$<CONFIG>"
            MINITUN_COMPILER="${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}"
            MINITUN_PROTOCOL_VERSION=1
    )
endfunction()
